#!/usr/bin/env bash
# installs and configures nginx

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo chmod -R 755 /var/www

sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"

service nginx start
