#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx

# echo 'Hello World!' > /var/www/html/index.html

redirString="server_name _;\n\trewrite ^/redirect_me https://github.com/x33zp permanent;"
sudo sed -i "s/server_name _;/$redirString/" /etc/nginx/sites-available/default

sudo service nginx restart
