#!/usr/bin/env bash
# install and configures HAproxy on a server

sudo apt-get update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

sudo bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
global
log 127.0.0.1 local0 notice
maxconn 2000
user haproxy
group haproxy

defaults
log global
mode http
option httplog
option dontlognull
retries 3
option redispatch
timeout connect 5000
timeout client 10000
timeout server 10000

listen hbnb
bind 0.0.0.0:80
mode http
stats enable
stats uri /haproxy?stats
balance roundrobin
option httpclose
option forwardfor
http-request set-header X-Forwarded-Port %[dst_port]
server 429583-web-01 100.25.180.67:80 check
server 429583-web-02 54.210.195.91:80 check
EOF'

sudo service haproxy restart
