#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.

# MySQL Credentials
user="root"
passwd="$1"

# Current date
date=$(date +'%d-%m-%Y')

# Backup file names
dump_file="backup.sql"
archive_file="$date.tar.gz"

# MySQL dump Command
mysqldump -u "$user" -p"passwd" --all-databases > "$dump_file"

# Compress dump_file into a tar.gz archive
tar -czvf "$archive_file" "$dump_file"

# Message
echo "$dump_file"
