#!/usr/bin/env bash
# This script Indefinitely writes "I am alive!" to the file "/tmp/my_process"
# In between every I am alive! message, the program should pause for 2 seconds

file=/tmp/my_process
string="I am alive!"

while true; do
    echo "$string" >> "$file"
    sleep 2
done
