#!/usr/bin/env bash
# This script displays numbers from 1 to 100:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

count=1
fizz="fizz"
buzz="buzz"
fizzbuzz="FizzBuzz"

while [ $count -le 100 ]; do
    if [ $((count % 15)) -eq 0 ]; then
        echo "$fizzbuzz"
    elif [ $((count % 3)) -eq 0 ]; then
        echo "$fizz"
    elif [ $((count % 5)) -eq 0 ]; then
        echo "$buzz"
    else
        echo "$count"
    fi
    ((count++))
done
