#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th loop iteration
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration

string1="bad luck from China"
string2="bad luck from Japan"
string3="bad luck from Italy"
count=1

while [ $count -lt 21 ]; do
    case "$count" in
        "4")
            echo "$count"
            echo "$string1"
            ;;
        "9")
            echo "$count"
            echo "$string2"
            ;;
        "17")
            echo "$count"
            echo "$string3"
            ;;
        *)
            echo "$count"
            ;;
    esac
    ((count++))
done
