#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed


ls [0-9]* > list

for i in `cat list`; do
    echo "$i" | cut -d '-' -f2
done    
