#!/usr/bin/env bash
# A bash script that runs nginx as user 'nginx' and listens at port 8080

service nginx stop

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 664 /etc/nginx/nginx.conf
pkill apache2

sudo -u nginx service nginx restart
